version: '3.8'

services:
  dev:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
      target: dev
    deploy:
      resources:
        reservations:
          devices:
            - capabilities:
                - gpu
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - .:/workspace
    command: sleep infinity

  app:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
      target: app
    deploy:
      resources:
        reservations:
          devices:
            - capabilities:
                - gpu
    networks:
      - shared
  eval:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
      target: dev
    deploy:
      resources:
        reservations:
          devices:
            - capabilities:
                - gpu
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./evaluation:/workspace
    command: sleep infinity
    networks:
      - shared
    depends_on:
      - app
  crag:
    build:
      context: ./evaluation/CRAG
      dockerfile: ./Dockerfile
    volumes:
      - ./evaluation/CRAG:/workspace
    command: sleep infinity
    networks:
      - shared
    depends_on:
      - app
networks:
  shared: