version: '3.8'

services:
  dev:
    build:
      context: .
      dockerfile: ./Dockerfile
      target: dev
    deploy:
      resources:
        reservations:
          devices:
            - capabilities:
                - gpu
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - .:/workspace
    command: sleep infinity

  api:
    build:
      context: .
      dockerfile: ./Dockerfile
      target: api
    deploy:
      resources:
        reservations:
          devices:
            - capabilities:
                - gpu
    networks:
      - shared

  eval:
    build:
      context: .
      dockerfile: ./Dockerfile
      target: dev
    deploy:
      resources:
        reservations:
          devices:
            - capabilities:
                - gpu
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./evaluation:/workspace
    command: sleep infinity
    networks:
      - shared
    depends_on:
      - api

  crag:
    build:
      context: ./evaluation/CRAG
      dockerfile: ./Dockerfile
    volumes:
      - ./evaluation/CRAG:/workspace
    command: sleep infinity
    networks:
      - shared
    depends_on:
      - api

  niah:
    build:
      context: .
      dockerfile: ./Dockerfile
      target: niah
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./evaluation/NIAH:/workspace
    command: sleep infinity
    depends_on:
      - api
    networks:
      - shared

networks:
  shared: