version: '3.8'

services:
  dev:
    build:
      context: ..
      dockerfile: .devcontainer/dev/Dockerfile
      target: dev
    deploy:
      resources:
        reservations:
          devices:
            - capabilities:
                - gpu
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ..:/workspace
    command: sleep infinity

  app:
    build:
      context: ..
      dockerfile: .devcontainer/dev/Dockerfile
      target: app
    deploy:
      resources:
        reservations:
          devices:
            - capabilities:
                - gpu
    ports:
      - 3024:2024
    networks:
      - shared
  eval:
    build:
      context: .
      dockerfile: eval/Dockerfile
    deploy:
      resources:
        reservations:
          devices:
            - capabilities:
                - gpu
    volumes:
      - ../evaluation:/workspace
    command: sleep infinity
    networks:
      - shared
    depends_on:
      - app
networks:
  shared: